### ISSUE TITLE
python-onvif doesn't work with python 3

### ISSUE THREAD

**Issue by bgoldsch** [quatanium/python-onvif#26]
I have a program that works fine with python 2.7
If I try to start this, I get an error message: 
>>> from types import InstanceType
>>> ImportError: cannot import name 'InstanceType'

Does some plan to convert the onvif module to python 3?

Best regard
Bernd

**Comment by HyperDevil** [comment]
Need python 3 version, anything else is just ridiculous.

**Comment by FalkTannhaeuser** [comment]
Please feel free to check the fork https://github.com/FalkTannhaeuser/python-onvif-zeep
I replaced the SOAP client suds (https://pypi.python.org/pypi/suds, Python 2 only and not longer maintained) by zeep (http://docs.python-zeep.org). Although not yet perfect, it works now both with Python 2 and Python 3.
